[package]
name = "leveldb-rs"
version = "0.1.0"
authors = ["kingeasternsun <kingeasternsun@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
thiserror = "1.0.30"
rand = "0.8.4"